### ISSUE TITLE
Update Typoscript Reference for 10.4

### ISSUE THREAD

**Issue by IndyIndyIndy** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#317]
https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/UsingSetting/TheConstantEditor.html
- [x] The ts „styles.content.textStyle“ in the example no longer exists. Switch it out with something that exists to avoid confusion?

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Setup/Config/Index.html
- [x]  **content_from_pid_allowOutsideDomain** was removed in 10.3
- [x]  **formMailCharset** no longer exists
- [x]  **ftu** no longer exists since 10.0

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/CoaAndCoaInt/Index.html
- [x]  Simplify example. GMENU no longer exists.

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Content/Index.html
- [x]  Example 2 is very confusing for users of recent TYPO3 versions, as it appears to take into account that the long obsolete ext:css_styled_content is installed.

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Editpanel/Index.html
- [x]  A bunch of options here appears to no longer exist: edit.displayRecord, printBeforeContent, previewBorder
- [x]  Could be related to the removed ext:feedit. But they could still be used by third-party feedit and other third-party frontend extensions. There should probably be an infobox about that.

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Hmenu/Index.html
- [x]  Remove mentions of GMENU
- [x]  Switch out GMENU examples with working examples

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/MenuObjects/CommonProperties/Index.html
- [x]  mark imgNamePrefix and imgNameNotRandom as removed
- [x]  These item states have been removed:
* IFSUBRO
* ACTRO
* ACTIFSUBRO
* CURRO
* CURIFSUBRO
* USRRO
* USERDEF1RO
* USERDEF2RO

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/MenuObjects/Gmenu/Index.html
- [x]  mark as removed

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/MenuObjects/Gmenuitem/Index.html
- [x]  Mark as removed

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/MenuObjects/Tmenuitem/Index.html
- [x]  The following options have been removed:
* RO_chBgColor
* beforeImg
* beforeImgTagParams
* beforeImgLink
* beforeROImg
* RO
* afterImg
* afterImgTagParams
* afterImgLink
* afterROImg

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/MenuObjects/Imgmenu/Index.html
- [x]  mark as removed

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/MenuObjects/Imgmenuitem/Index.html
- [x]  mark as removed

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Functions/Addparams.html
- [x]  mark as removed

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Functions/Imgresource.html
- [x]  alternativeTempPath no longer exists?

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Functions/Stdwrap.html
- [x]  mark filelink as removed

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Conditions/Index.html
- [ ]  Provide a comparison between old and new syntax for all the conditions to make migration easier

- [x]  Check for remaining occurences of GMENU, IMGMENU

**Comment by sypets** [comment]
@IndyIndyIndy Do you plan to work on this?

If yes, we can assign you to the issue and here are some tips:

About marking deprecated stuff and removing (breaking) changes: Current practice is 

* if deprecated, add a note that it is deprecated and since when (you can use version hints and add link to changelog), see https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/Index.html
* if breaking, just remove it (without adding a note)

as defined here:

* conventions: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/Index.html
* upgrading docs based on changelogs: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/HowToUpdateDocs.html

Also, there are already issues existing for changelogs:

* [10.4](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/885)
* other issues with "changelog" label: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues

However, this has the disadvantage, that you need write access to the repo to check off the checkmarks. 

Feel free to contact me on Slack!

**Comment by sypets** [comment]
It looks like this is done. closing.
